---
services:
  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_API_BASE_URL=https://localhost

  backend:
    build:
      context: ./backend
    expose:
      - "3001"
    ports:
      - "3001:3001"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bloopdb
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bloopdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  proxy:
    build:
      context: ./proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
