services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    networks:
      - app-network
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/certs:/etc/nginx/certs

networks:
  app-network:
    driver: bridge
    